#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROMPTS_DIR="$REPO_ROOT/docs/builtin-agent-prompts"
CHECK_MODE="${1:-}"

if [ ! -d "$PROMPTS_DIR" ]; then
  echo "Missing prompts directory: $PROMPTS_DIR" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d "$REPO_ROOT/src/.gen_agent_builtins_XXXXXX")"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

python3 - "$PROMPTS_DIR" "$TMP_DIR" <<'PY'
import sys
import os
import re

prompts_dir = sys.argv[1]
output_dir = sys.argv[2]

# Canonical agent order (matches `all` list in the generated file)
AGENT_ORDER = [
    "ceo", "team-lead", "reviewer", "researcher",
    "tester", "coder", "planner", "debugger",
    "refactorer", "documenter", "ops",
]

GROUPS = [
    ("coordination", "Agent_template_builtins_coordination",
     ["ceo", "team-lead", "reviewer"]),
    ("research", "Agent_template_builtins_research",
     ["researcher", "tester"]),
    ("execution", "Agent_template_builtins_execution",
     ["coder", "planner", "debugger"]),
    ("maintenance", "Agent_template_builtins_maintenance",
     ["refactorer", "documenter", "ops"]),
]

# OCaml variable name for each agent (team-lead -> team_lead)
def ocaml_var(name):
    return name.replace("-", "_")

# Map YAML role string to OCaml constructor
ROLE_MAP = {
    "ceo": "Ceo", "team_lead": "Team_lead", "reviewer": "Reviewer",
    "coder": "Coder", "planner": "Planner", "debugger": "Debugger",
    "researcher": "Researcher", "tester": "Tester", "refactorer": "Refactorer",
    "documenter": "Documenter", "ops": "Ops",
}

def role_to_ocaml(role_str):
    key = role_str.strip().lower().replace("-", "_")
    return ROLE_MAP.get(key, role_str.strip())

def parse_md(path):
    with open(path, "r") as f:
        content = f.read()

    if not content.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")

    end = content.index("\n---\n", 3)
    fm_text = content[4:end]
    body = content[end + 5:].strip()

    # Parse frontmatter — supports simple scalars and YAML lists
    pairs = {}
    current_key = None
    current_list = None

    for line in fm_text.splitlines():
        list_item = re.match(r"^  - (.+)$", line)
        key_val = re.match(r"^(\w[\w-]*):\s*(.*)$", line)

        if list_item and current_list is not None:
            current_list.append(list_item.group(1).strip())
        elif key_val:
            if current_list is not None:
                pairs[current_key] = current_list
            current_key = key_val.group(1)
            value = key_val.group(2).strip()
            if value == "":
                current_list = []
            elif value == "[]":
                current_list = []
                pairs[current_key] = []
                current_list = None
                current_key = None
            else:
                current_list = None
                pairs[current_key] = value

    if current_list is not None and current_key is not None:
        pairs[current_key] = current_list

    return pairs, body

def ocaml_qstring(s):
    """Wrap s in an OCaml quoted string {|...|}, checking for the delimiter."""
    tag = ""
    # Find a tag that doesn't appear in s as "|tag}"
    while ("|" + tag + "}") in s:
        tag += "x"
    return "{" + tag + "|" + s + "|" + tag + "}"

def ocaml_strlist(items):
    if not items:
        return "[]"
    inner = "; ".join(f'"{x}"' for x in items)
    return "[ " + inner + " ]"

agents = []
for name in AGENT_ORDER:
    path = os.path.join(prompts_dir, name + ".md")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing: {path}")
    pairs, body = parse_md(path)
    agents.append((name, pairs, body))

agents_by_name = {name: (pairs, body) for name, pairs, body in agents}

def header(filename):
    return [
        f"(* {filename} — generated by scripts/gen_agent_builtins.sh *)",
        "(* DO NOT EDIT MANUALLY — edit docs/builtin-agent-prompts/*.md instead *)",
        "",
    ]

def append_agent(lines, name, pairs, body):
    var = ocaml_var(name)
    role = role_to_ocaml(pairs.get("role", name))
    description = pairs.get("description", "")
    goal = pairs.get("goal", "")
    backstory = pairs.get("backstory", "")
    allowed = pairs.get("allowed_tools", [])
    disallowed = pairs.get("disallowed_tools", [])

    lines.append(f"let {var} =")
    lines.append(f"  mk ~name:{ocaml_qstring(name)}")
    lines.append(f"    ~description:{ocaml_qstring(description)}")
    lines.append(f"    ~role:Agent_template.{role}")
    lines.append(f"    ~goal:{ocaml_qstring(goal)}")
    lines.append(f"    ~backstory:{ocaml_qstring(backstory)}")
    lines.append(f"    ~system_prompt:{ocaml_qstring(body)}")
    lines.append(f"    ~allowed_tools:{ocaml_strlist(allowed)}")
    lines.append(f"    ~disallowed_tools:{ocaml_strlist(disallowed)}")
    lines.append("")

generated = {}

common_lines = header("agent_template_builtins_common.ml")
common_lines.append("let mk ~name ~description ~role ~goal ~backstory ~system_prompt ~allowed_tools")
common_lines.append("    ~disallowed_tools =")
common_lines.append("  {")
common_lines.append("    Agent_template.name;")
common_lines.append("    description;")
common_lines.append("    role;")
common_lines.append("    goal;")
common_lines.append("    backstory;")
common_lines.append("    system_prompt;")
common_lines.append("    model = None;")
common_lines.append("    max_tool_iterations = None;")
common_lines.append("    allowed_tools;")
common_lines.append("    disallowed_tools;")
common_lines.append("    tool_search_enabled = None;")
common_lines.append("    reasoning_effort = None;")
common_lines.append("    cwd = None;")
common_lines.append("    source = Builtin;")
common_lines.append("    metadata = [];")
common_lines.append("  }")
common_lines.append("")
generated["agent_template_builtins_common.ml"] = common_lines

for suffix, _, names in GROUPS:
    filename = f"agent_template_builtins_{suffix}.ml"
    lines = header(filename)
    lines.append("open Agent_template_builtins_common")
    lines.append("")
    for name in names:
        pairs, body = agents_by_name[name]
        append_agent(lines, name, pairs, body)
    generated[filename] = lines

lines = header("agent_template_builtins.ml")
lines.append("include Agent_template_builtins_common")
for _, module_name, _ in GROUPS:
    lines.append(f"include {module_name}")
lines.append("")
lines.append("let all =")
lines.append("  [")
for name, _, _ in agents:
    lines.append(f"    {ocaml_var(name)};")
lines.append("  ]")
lines.append("")
lines.append("let find name =")
lines.append("  let name_lower = String.lowercase_ascii name in")
lines.append("  List.find_opt")
lines.append("    (fun (t : Agent_template.t) -> String.lowercase_ascii t.name = name_lower)")
lines.append("    all")
lines.append("")
lines.append("let () = Agent_template.builtins_ref := all")
lines.append("")
generated["agent_template_builtins.ml"] = lines

for filename, lines in generated.items():
    with open(os.path.join(output_dir, filename), "w") as f:
        f.write("\n".join(lines) + "\n")
PY

OPAM_SWITCH="${OPAM_SWITCH:-$(opam switch show 2>/dev/null || true)}"
if [ -n "$OPAM_SWITCH" ]; then
  OCAMLFORMAT="$(opam exec --switch="$OPAM_SWITCH" -- which ocamlformat 2>/dev/null || echo "")"
else
  OCAMLFORMAT="$(command -v ocamlformat 2>/dev/null || echo "")"
fi

if [ -n "$OCAMLFORMAT" ]; then
  for tmp_file in "$TMP_DIR"/*.ml; do
    "$OCAMLFORMAT" -i "$tmp_file" 2>/dev/null || true
  done
fi

if [ "$CHECK_MODE" = "--check" ]; then
  status=0
  for tmp_file in "$TMP_DIR"/*.ml; do
    output="$REPO_ROOT/src/$(basename "$tmp_file")"
    if ! diff -q "$tmp_file" "$output" >/dev/null 2>&1; then
      echo "$(basename "$output") is out of date. Run 'make gen-agents' to regenerate." >&2
      diff "$tmp_file" "$output" || true
      status=1
    fi
  done
  if [ "$status" -eq 0 ]; then
    echo "agent template builtins are up to date."
  fi
  exit "$status"
else
  for tmp_file in "$TMP_DIR"/*.ml; do
    output="$REPO_ROOT/src/$(basename "$tmp_file")"
    mv "$tmp_file" "$output"
    echo "Generated $output"
  done
fi
