#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROMPTS_DIR="$REPO_ROOT/docs/builtin-agent-prompts"
OUTPUT="$REPO_ROOT/src/agent_template_builtins.ml"
CHECK_MODE="${1:-}"

if [ ! -d "$PROMPTS_DIR" ]; then
  echo "Missing prompts directory: $PROMPTS_DIR" >&2
  exit 1
fi

TMP_OUTPUT="$(mktemp "$REPO_ROOT/src/.gen_agent_builtins_XXXXXX.ml")"

python3 - "$PROMPTS_DIR" >"$TMP_OUTPUT" <<'PY'
import sys
import os
import re

prompts_dir = sys.argv[1]

# Canonical agent order (matches `all` list in the generated file)
AGENT_ORDER = [
    "ceo", "team-lead", "reviewer", "researcher",
    "tester", "coder", "planner", "debugger",
    "refactorer", "documenter", "ops",
]

# OCaml variable name for each agent (team-lead -> team_lead)
def ocaml_var(name):
    return name.replace("-", "_")

# Map YAML role string to OCaml constructor
ROLE_MAP = {
    "ceo": "Ceo", "team_lead": "Team_lead", "reviewer": "Reviewer",
    "coder": "Coder", "planner": "Planner", "debugger": "Debugger",
    "researcher": "Researcher", "tester": "Tester", "refactorer": "Refactorer",
    "documenter": "Documenter", "ops": "Ops",
}

def role_to_ocaml(role_str):
    key = role_str.strip().lower().replace("-", "_")
    return ROLE_MAP.get(key, role_str.strip())

def parse_md(path):
    with open(path, "r") as f:
        content = f.read()

    if not content.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")

    end = content.index("\n---\n", 3)
    fm_text = content[4:end]
    body = content[end + 5:].strip()

    # Parse frontmatter — supports simple scalars and YAML lists
    pairs = {}
    current_key = None
    current_list = None

    for line in fm_text.splitlines():
        list_item = re.match(r"^  - (.+)$", line)
        key_val = re.match(r"^(\w[\w-]*):\s*(.*)$", line)

        if list_item and current_list is not None:
            current_list.append(list_item.group(1).strip())
        elif key_val:
            if current_list is not None:
                pairs[current_key] = current_list
            current_key = key_val.group(1)
            value = key_val.group(2).strip()
            if value == "":
                current_list = []
            elif value == "[]":
                current_list = []
                pairs[current_key] = []
                current_list = None
                current_key = None
            else:
                current_list = None
                pairs[current_key] = value

    if current_list is not None and current_key is not None:
        pairs[current_key] = current_list

    return pairs, body

def ocaml_qstring(s):
    """Wrap s in an OCaml quoted string {|...|}, checking for the delimiter."""
    tag = ""
    # Find a tag that doesn't appear in s as "|tag}"
    while ("|" + tag + "}") in s:
        tag += "x"
    return "{" + tag + "|" + s + "|" + tag + "}"

def ocaml_strlist(items):
    if not items:
        return "[]"
    inner = "; ".join(f'"{x}"' for x in items)
    return "[ " + inner + " ]"

agents = []
for name in AGENT_ORDER:
    path = os.path.join(prompts_dir, name + ".md")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing: {path}")
    pairs, body = parse_md(path)
    agents.append((name, pairs, body))

lines = []
lines.append("(* agent_template_builtins.ml — generated by scripts/gen_agent_builtins.sh *)")
lines.append("(* DO NOT EDIT MANUALLY — edit docs/builtin-agent-prompts/*.md instead *)")
lines.append("")
lines.append("let mk ~name ~description ~role ~goal ~backstory ~system_prompt ~allowed_tools")
lines.append("    ~disallowed_tools =")
lines.append("  {")
lines.append("    Agent_template.name;")
lines.append("    description;")
lines.append("    role;")
lines.append("    goal;")
lines.append("    backstory;")
lines.append("    system_prompt;")
lines.append("    model = None;")
lines.append("    max_tool_iterations = None;")
lines.append("    allowed_tools;")
lines.append("    disallowed_tools;")
lines.append("    tool_search_enabled = None;")
lines.append("    reasoning_effort = None;")
lines.append("    source = Builtin;")
lines.append("    metadata = [];")
lines.append("  }")
lines.append("")

for name, pairs, body in agents:
    var = ocaml_var(name)
    role = role_to_ocaml(pairs.get("role", name))
    description = pairs.get("description", "")
    goal = pairs.get("goal", "")
    backstory = pairs.get("backstory", "")
    allowed = pairs.get("allowed_tools", [])
    disallowed = pairs.get("disallowed_tools", [])

    lines.append(f"let {var} =")
    lines.append(f"  mk ~name:{ocaml_qstring(name)}")
    lines.append(f"    ~description:{ocaml_qstring(description)}")
    lines.append(f"    ~role:Agent_template.{role}")
    lines.append(f"    ~goal:{ocaml_qstring(goal)}")
    lines.append(f"    ~backstory:{ocaml_qstring(backstory)}")
    lines.append(f"    ~system_prompt:{ocaml_qstring(body)}")
    lines.append(f"    ~allowed_tools:{ocaml_strlist(allowed)}")
    lines.append(f"    ~disallowed_tools:{ocaml_strlist(disallowed)}")
    lines.append("")

lines.append("let all =")
lines.append("  [")
for name, _, _ in agents:
    lines.append(f"    {ocaml_var(name)};")
lines.append("  ]")
lines.append("")
lines.append("let find name =")
lines.append("  let name_lower = String.lowercase_ascii name in")
lines.append("  List.find_opt")
lines.append("    (fun (t : Agent_template.t) -> String.lowercase_ascii t.name = name_lower)")
lines.append("    all")
lines.append("")
lines.append("let () = Agent_template.builtins_ref := all")
lines.append("")

print("\n".join(lines))
PY

OCAMLFORMAT="$(opam exec --switch=clawq-5.1 -- which ocamlformat 2>/dev/null || echo "")"

if [ -n "$OCAMLFORMAT" ]; then
  "$OCAMLFORMAT" -i "$TMP_OUTPUT" 2>/dev/null || true
fi

if [ "$CHECK_MODE" = "--check" ]; then
  if diff -q "$TMP_OUTPUT" "$OUTPUT" >/dev/null 2>&1; then
    echo "agent_template_builtins.ml is up to date."
    rm "$TMP_OUTPUT"
    exit 0
  else
    echo "agent_template_builtins.ml is out of date. Run 'make gen-agents' to regenerate." >&2
    diff "$TMP_OUTPUT" "$OUTPUT" || true
    rm "$TMP_OUTPUT"
    exit 1
  fi
else
  mv "$TMP_OUTPUT" "$OUTPUT"
  echo "Generated $OUTPUT"
fi
