(* agent_template_builtins.ml — generated by scripts/gen_agent_builtins.sh *)
(* DO NOT EDIT MANUALLY — edit docs/builtin-agent-prompts/*.md instead *)

include Agent_template_builtins_common
include Agent_template_builtins_coordination
include Agent_template_builtins_research
include Agent_template_builtins_execution
include Agent_template_builtins_maintenance

let all =
  [
    ceo;
    team_lead;
    reviewer;
    researcher;
    tester;
    coder;
    planner;
    debugger;
    refactorer;
    documenter;
    ops;
  ]

let find name =
  let name_lower = String.lowercase_ascii name in
  List.find_opt
    (fun (t : Agent_template.t) -> String.lowercase_ascii t.name = name_lower)
    all

let () = Agent_template.builtins_ref := all
