(* agent_template_builtins_common.ml — generated by scripts/gen_agent_builtins.sh *)
(* DO NOT EDIT MANUALLY — edit docs/builtin-agent-prompts/*.md instead *)

let mk ~name ~description ~role ~goal ~backstory ~system_prompt ~allowed_tools
    ~disallowed_tools =
  {
    Agent_template.name;
    description;
    role;
    goal;
    backstory;
    system_prompt;
    model = None;
    max_tool_iterations = None;
    allowed_tools;
    disallowed_tools;
    tool_search_enabled = None;
    reasoning_effort = None;
    cwd = None;
    source = Builtin;
    metadata = [];
  }
